name: Wine Inference Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Daily at 2am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        working-directory: ./wine
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        working-directory: ./wine
        run: python wine-inference-pipeline.py
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
